apiVersion: v1
kind: Service
metadata:
  name: {{ include "ofa-center.fullname" . }}
  labels:
    {{- include "ofa-center.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      name: grpc
    - port: {{ .Values.service.wsPort }}
      targetPort: ws
      name: ws
  selector:
    {{- include "ofa-center.selectorLabels" . | nindent 4 }}
