// Package codegen - 代码生成器
// Sprint 31: v9.0 自动代码生成
package codegen

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"text/template"
	"time"
)

// Generator 代码生成器
type Generator struct {
	config     GeneratorConfig
	templates  *TemplateRegistry
	formatters map[string]Formatter
	stats      *GeneratorStats
	mu         sync.RWMutex
}

// GeneratorConfig 生成器配置
type GeneratorConfig struct {
	OutputDir      string            `json:"output_dir"`
	TemplateDir    string            `json:"template_dir"`
	FileHeader     string            `json:"file_header"`
	FormatOnSave   bool              `json:"format_on_save"`
	Overwrite      bool              `json:"overwrite"`
	Variables      map[string]string `json:"variables"`
}

// DefaultGeneratorConfig 默认配置
func DefaultGeneratorConfig() GeneratorConfig {
	return GeneratorConfig{
		OutputDir:    "./generated",
		TemplateDir:  "./templates",
		FileHeader:   "// Code generated by OFA Codegen. DO NOT EDIT.",
		FormatOnSave: true,
		Overwrite:    false,
		Variables:    make(map[string]string),
	}
}

// GeneratorStats 生成器统计
type GeneratorStats struct {
	FilesGenerated int64 `json:"files_generated"`
	LinesGenerated int64 `json:"lines_generated"`
	TemplatesUsed  int64 `json:"templates_used"`
	Errors         int64 `json:"errors"`
}

// NewGenerator 创建生成器
func NewGenerator(config GeneratorConfig) *Generator {
	g := &Generator{
		config:     config,
		templates:  NewTemplateRegistry(),
		formatters: make(map[string]Formatter),
		stats:      &GeneratorStats{},
	}

	// 注册默认格式化器
	g.RegisterFormatter("go", &GoFormatter{})
	g.RegisterFormatter("ts", &TypeScriptFormatter{})
	g.RegisterFormatter("java", &JavaFormatter{})
	g.RegisterFormatter("py", &PythonFormatter{})
	g.RegisterFormatter("rs", &RustFormatter{})

	return g
}

// RegisterTemplate 注册模板
func (g *Generator) RegisterTemplate(name, content string) error {
	return g.templates.Register(name, content)
}

// RegisterFormatter 注册格式化器
func (g *Generator) RegisterFormatter(ext string, f Formatter) {
	g.formatters[ext] = f
}

// Generate 生成代码
func (g *Generator) Generate(templateName string, data interface{}, outputPath string) error {
	g.mu.Lock()
	defer g.mu.Unlock()

	// 检查文件是否存在
	if !g.config.Overwrite {
		if _, err := os.Stat(outputPath); err == nil {
			return fmt.Errorf("文件已存在: %s", outputPath)
		}
	}

	// 获取模板
	tmpl, err := g.templates.Get(templateName)
	if err != nil {
		return fmt.Errorf("模板不存在: %s", templateName)
	}

	// 合并变量
	mergedData := g.mergeData(data)

	// 执行模板
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, mergedData); err != nil {
		g.stats.Errors++
		return fmt.Errorf("模板执行失败: %w", err)
	}

	content := buf.String()

	// 添加文件头
	if g.config.FileHeader != "" {
		ext := filepath.Ext(outputPath)
		content = g.addHeader(content, ext)
	}

	// 格式化
	if g.config.FormatOnSave {
		ext := strings.TrimPrefix(filepath.Ext(outputPath), ".")
		if f, ok := g.formatters[ext]; ok {
			formatted, err := f.Format(content)
			if err == nil {
				content = formatted
			}
		}
	}

	// 写入文件
	os.MkdirAll(filepath.Dir(outputPath), 0755)
	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		g.stats.Errors++
		return fmt.Errorf("写入文件失败: %w", err)
	}

	g.stats.FilesGenerated++
	g.stats.LinesGenerated += int64(strings.Count(content, "\n"))
	g.stats.TemplatesUsed++

	return nil
}

// GenerateBatch 批量生成
func (g *Generator) GenerateBatch(tasks []GenerateTask) error {
	for _, task := range tasks {
		if err := g.Generate(task.Template, task.Data, task.Output); err != nil {
			return fmt.Errorf("生成 %s 失败: %w", task.Output, err)
		}
	}
	return nil
}

// mergeData 合并数据
func (g *Generator) mergeData(data interface{}) map[string]interface{} {
	result := make(map[string]interface{})

	// 添加全局变量
	for k, v := range g.config.Variables {
		result[k] = v
	}

	// 添加时间信息
	result["GeneratedAt"] = time.Now().Format(time.RFC3339)
	result["Year"] = time.Now().Year()

	// 合并传入数据
	if m, ok := data.(map[string]interface{}); ok {
		for k, v := range m {
			result[k] = v
		}
	}

	return result
}

// addHeader 添加文件头
func (g *Generator) addHeader(content, ext string) string {
	header := g.config.FileHeader

	switch ext {
	case ".go":
		return header + "\n\n" + content
	case ".ts", ".js":
		return "// " + header + "\n\n" + content
	case ".py":
		return "# " + header + "\n\n" + content
	case ".java":
		return "// " + header + "\n\n" + content
	case ".rs":
		return "// " + header + "\n\n" + content
	default:
		return header + "\n\n" + content
	}
}

// GetStats 获取统计
func (g *Generator) GetStats() *GeneratorStats {
	return g.stats
}

// GenerateTask 生成任务
type GenerateTask struct {
	Template string      `json:"template"`
	Data     interface{} `json:"data"`
	Output   string      `json:"output"`
}

// Formatter 格式化器接口
type Formatter interface {
	Format(content string) (string, error)
}

// GoFormatter Go格式化器
type GoFormatter struct{}

func (f *GoFormatter) Format(content string) (string, error) {
	// 简化实现：实际应使用go/format
	return content, nil
}

// TypeScriptFormatter TypeScript格式化器
type TypeScriptFormatter struct{}

func (f *TypeScriptFormatter) Format(content string) (string, error) {
	return content, nil
}

// JavaFormatter Java格式化器
type JavaFormatter struct{}

func (f *JavaFormatter) Format(content string) (string, error) {
	return content, nil
}

// PythonFormatter Python格式化器
type PythonFormatter struct{}

func (f *PythonFormatter) Format(content string) (string, error) {
	return content, nil
}

// RustFormatter Rust格式化器
type RustFormatter struct{}

func (f *RustFormatter) Format(content string) (string, error) {
	return content, nil
}

// TemplateRegistry 模板注册表
type TemplateRegistry struct {
	templates map[string]*template.Template
	mu        sync.RWMutex
}

// NewTemplateRegistry 创建模板注册表
func NewTemplateRegistry() *TemplateRegistry {
	return &TemplateRegistry{
		templates: make(map[string]*template.Template),
	}
}

// Register 注册模板
func (r *TemplateRegistry) Register(name, content string) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	tmpl, err := template.New(name).Parse(content)
	if err != nil {
		return fmt.Errorf("模板解析失败: %w", err)
	}

	r.templates[name] = tmpl
	return nil
}

// Get 获取模板
func (r *TemplateRegistry) Get(name string) (*template.Template, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	tmpl, ok := r.templates[name]
	if !ok {
		return nil, fmt.Errorf("模板不存在: %s", name)
	}

	return tmpl, nil
}

// List 列出模板
func (r *TemplateRegistry) List() []string {
	r.mu.RLock()
	defer r.mu.RUnlock()

	names := make([]string, 0, len(r.templates))
	for name := range r.templates {
		names = append(names, name)
	}
	return names
}

// 预置模板

var DefaultTemplates = map[string]string{
	// Go模型模板
	"go-model": `package {{.Package}}

// {{.Name}} {{.Description}}
type {{.Name}} struct {
{{- range .Fields}}
	{{.Name}} {{.Type}} ` + "`" + `json:"{{.JSONName}}"{{if .Description}} // {{.Description}}{{end}}` + "`" + `
{{- end}}
}

// TableName 返回表名
func (m *{{.Name}}) TableName() string {
	return "{{.TableName}}"
}
`,
	// Go接口模板
	"go-interface": `package {{.Package}}

// {{.Name}} {{.Description}}
type {{.Name}} interface {
{{- range .Methods}}
	// {{.Name}} {{.Description}}
	{{.Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{$p.Name}} {{$p.Type}}{{end}}) {{.ReturnType}}
{{- end}}
}
`,
	// TypeScript接口模板
	"ts-interface": `/**
 * {{.Description}}
 */
export interface {{.Name}} {
{{- range .Fields}}
  {{.Name}}: {{.Type}};{{if .Description}} // {{.Description}}{{end}}
{{- end}}
}
`,
	// Java类模板
	"java-class": `package {{.Package}};

/**
 * {{.Description}}
 */
public class {{.Name}} {
{{- range .Fields}}
    private {{.Type}} {{.NameLower}};
{{- end}}

{{- range .Fields}}
    public {{.Type}} get{{.Name}}() {
        return {{.NameLower}};
    }

    public void set{{.Name}}({{.Type}} {{.NameLower}}) {
        this.{{.NameLower}} = {{.NameLower}};
    }
{{- end}}
}
`,
	// Python类模板
	"py-class": `"""{{.Description}}"""
from dataclasses import dataclass
from typing import Optional

@dataclass
class {{.Name}}:
    """{{.Description}}"""
{{- range .Fields}}
    {{.Name}}: {{.Type}}{{if .Default}} = {{.Default}}{{end}}
{{- end}}
`,
	// API处理器模板
	"go-api-handler": `package {{.Package}}

import (
	"encoding/json"
	"net/http"
)

// {{.HandlerName}} 处理{{.Description}}
func {{.HandlerName}}(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		{{.HandlerName}}Get(w, r)
	case http.MethodPost:
		{{.HandlerName}}Post(w, r)
	case http.MethodPut:
		{{.HandlerName}}Put(w, r)
	case http.MethodDelete:
		{{.HandlerName}}Delete(w, r)
	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func {{.HandlerName}}Get(w http.ResponseWriter, r *http.Request) {
	// TODO: 实现GET逻辑
	json.NewEncoder(w).Encode(map[string]string{"message": "{{.HandlerName}} GET"})
}

func {{.HandlerName}}Post(w http.ResponseWriter, r *http.Request) {
	// TODO: 实现POST逻辑
	json.NewEncoder(w).Encode(map[string]string{"message": "{{.HandlerName}} POST"})
}
`,
	// SDK客户端模板
	"sdk-client": `package {{.Package}}

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

// Client {{.Name}}客户端
type Client struct {
	baseURL    string
	httpClient *http.Client
	apiKey     string
}

// NewClient 创建客户端
func NewClient(baseURL, apiKey string) *Client {
	return &Client{
		baseURL: baseURL,
		apiKey:  apiKey,
		httpClient: &http.Client{
			Timeout: 30 * time.Second,
		},
	}
}

{{- range .Methods}}
// {{.Name}} {{.Description}}
func (c *Client) {{.Name}}(ctx context.Context{{range .Params}}, {{.Name}} {{.Type}}{{end}}) ({{.ReturnType}}, error) {
	var result {{.ReturnType}}
	// TODO: 实现API调用
	return result, nil
}
{{- end}}
`,
}

// InitDefaultTemplates 初始化默认模板
func (g *Generator) InitDefaultTemplates() error {
	for name, content := range DefaultTemplates {
		if err := g.RegisterTemplate(name, content); err != nil {
			return err
		}
	}
	return nil
}

// LoadTemplatesFromDir 从目录加载模板
func (g *Generator) LoadTemplatesFromDir(dir string) error {
	files, err := filepath.Glob(filepath.Join(dir, "*.tmpl"))
	if err != nil {
		return err
	}

	for _, file := range files {
		content, err := os.ReadFile(file)
		if err != nil {
			return err
		}

		name := strings.TrimSuffix(filepath.Base(file), ".tmpl")
		if err := g.RegisterTemplate(name, string(content)); err != nil {
			return err
		}
	}

	return nil
}

// Write 输出到Writer
func (g *Generator) Write(templateName string, data interface{}, w io.Writer) error {
	tmpl, err := g.templates.Get(templateName)
	if err != nil {
		return err
	}

	mergedData := g.mergeData(data)
	return tmpl.Execute(w, mergedData)
}